version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "feed-importer-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-164ia1p6mdcrj"
s3_prefix = "feed-importer-stack"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
